### PR TITLE
Remove the developers page

### PR DESCRIPTION
**Pull request by DarthGandalf**
Code snippet like that will only get outdated, and it was not even about
developers.

Instead, point developers in Contribute to the source code

### CODE REVIEW

**Comment by Photon89** [comment]
I am not a developer so I have a hard time judging if the snippet is helpful for potential plugin authors and whether it is unusable already due to being out of date... Maybe we can put the snippet into the Wiki, in  case it is still usable: https://github.com/shutter-project/shutter/wiki ?

**Comment by DarthGandalf** [comment]
I don't know whether it's outdated already or not yet. If you think it's useful, let's put it to wiki, sure, but that won't stop it from bitrotting. At least, it definitily will be once I manage to finish the gtk3 branch.

Re wiki. Should its content be on the website instead?

**Comment by Photon89** [comment]
> At least, it definitily will be once I manage to finish the gtk3 branch.

I see.

> Re wiki. Should its content be on the website instead?

Sure, why not? Maybe in "FAQ & Help > Known issues"?

**Review by Photon89 — APPROVED** [review]

**Comment by DarthGandalf** [comment]
> Sure, why not? Maybe in "FAQ & Help > Known issues"?

Sounds fine. Please do

**Pull request merged**
