### PR TITLE
Make layout (URLs) more compatible with previous site

### PR DESCRIPTION
**Pull request by DarthGandalf**

### CODE REVIEW

**Comment by Photon89** [comment]
I think, we can remove the "In the news" sections since almost all the links in the old website point to dead ends and I hardly think that there was much news coverage for Shutter during the last few years. For the "Downloads" section there is also no proper content because we don't have a PPA any more. But I agree that the way it was before was bad since the hover-able entries of the top bar all had links pointing to nothing. I think, the best way to resolve the problem would be to somehow remove the links and make the entries non-clickable, but I don't know if it is possible without JS...

**Comment by DarthGandalf** [comment]
> I think, we can remove the "In the news"

Sounds good.

> For the "Downloads" section there is also no proper content because we don't have a PPA any more.

I agree. Which is why I made it the previous "third party" one. I've now also added the redirect from /downloads

> I think, the best way to resolve the problem would be to somehow remove the links and make the entries non-clickable, but I don't know if it is possible without JS...

The only link like that after this PR is "previews", and clickability has nothing to do with JS or not. Users can click anywhere. I think from UX point of view we still need to do something with the "previews". Either redo that menu somehow, or add a placeholder page with 2 links on it, though that's not great

**Comment by DarthGandalf** [comment]
Perhaps replace `reviews` with `screenshots` and `screenshots/screencasts`?

**Review by Photon89 — APPROVED** [review]

**Comment by Photon89** [comment]
Sorry for not replying earlier, I also didn't quite get what you meant in your last comment. But now I get it, looks good!

**Comment by DarthGandalf** [comment]
Yeah, that sentence was not easy to parse, sorry. Especially with the typo reviews/previews which I haven't noticed before

**Pull request merged**
