### PR TITLE
Add shutter logo

### LINKED ISSUE #4: The new website needs some branding
@vadi2 How should we proceed regarding styling/branding the new site?

### PR DESCRIPTION
**Pull request by DarthGandalf**
Close #4

### CODE REVIEW

**Comment by Photon89** [comment]
What about showing this cyan hero thingy on the main page only? Then we could but a bit more than the logo into it, maybe some screenshot collage?

**Comment by DarthGandalf** [comment]
With this change you might want to also remove the custom hero.html I added. That file was mostly there for the shutter.svg I took from /usr/share, because the default bulma's one didn't work well with it

**Comment by Photon89** [comment]
Mhh, somehow the collage looks worse than I expected... Any thoughts if something can be improved, or better return to the plain logo version?

**Comment by DarthGandalf** [comment]
Um, yeah, now the website looks like it's selling cars.

**Comment by Photon89** [comment]
Good point. I thought, the yellow car in some of the screenshots on the preview page was quite nice as picture material for shutter, but maybe putting a car in each of the collage screenshots was a bad idea. :smile:  What else, besides of too many cars?

**Review by vadi2 — APPROVED** [review]

**Pull request merged**
