### PR TITLE
Move about page to front

### PR DESCRIPTION
**Pull request by DarthGandalf**

### CODE REVIEW

**Comment by DarthGandalf** [comment]
@vadi2 I haven't realized you were copying the text from About page there. Please take a look here.

@mheffner do you know how to make redirect from https://deploy-preview-36--shutter-new-website.netlify.app/about/ to also work? Currently it works only without the ending `/`

**Review by vadi2 — APPROVED** [review]

**Review by Photon89 — APPROVED** [review]
Yeah, much better this way!

**Comment by mheffner** [comment]
> @mheffner do you know how to make redirect from https://deploy-preview-36--shutter-new-website.netlify.app/about/ to also work? Currently it works only without the ending `/`

@DarthGandalf I believe the redirect processing works in-order, with the first matching rule triggering. So, if you moved the team page directs to the top, I wonder if you could handle this with a direct at the end of:

```
[[redirects]]
  from = "/about*"
  to = "/"
  force = true
```

**Comment by mheffner** [comment]
Actually it seems to already work for me? This says the processing should work the same for both: https://docs.netlify.com/routing/redirects/redirect-options/#trailing-slash

**Comment by DarthGandalf** [comment]
Weird. It didn't work for me before, but now it does, without me pushing any new commit

**Pull request merged**
