### PR TITLE
Add Netlify

### PR DESCRIPTION
**Pull request by mheffner**
WIP: broken right now without a Gemfile I believe

Publishes to: https://shutter-new-website.netlify.app/

### CODE REVIEW

**Comment by DarthGandalf** [comment]
I have a Gemfile added in #1

**Comment by mheffner** [comment]
@DarthGandalf cool, just rebased onto that branch

**Comment by mheffner** [comment]
Failing with:
```
9:14:09 AM:         Pagination: Pagination is enabled, but I couldn't find an index.html page to use as the pagination template. Skipping pagination.
   GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
9:14:09 AM:    GitHub Metadata: Error processing value 'description':
9:14:09 AM:   Liquid Exception: No repo name found. Specify using PAGES_REPO_NWO environment variables, 'repository' in your configuration, or set up an 'origin' git remote pointing to your github.com repository. in /_layouts/default.html
9:14:09 AM:              ERROR: YOUR SITE COULD NOT BE BUILT:
9:14:09 AM:                     ------------------------------------
9:14:09 AM:                     No repo name found. Specify using PAGES_REPO_NWO environment variables, 'repository' in your configuration, or set up an 'origin' git remote pointing to your github.com repository.
```

Feel free to grab the commits here if you want to debug, I may be away from the keys for a bit.

**Comment by DarthGandalf** [comment]
There is no error anymore, but it seems to deploy the wrong website.

**Comment by Photon89** [comment]
I must admit, the whole Netlify thing is way over my head and I absolutely don't know how this could have happened, so, guys, please have a look into it when you have a free minute for it!

**Comment by mheffner** [comment]
Ok, I think this is fixed now. The PR deploy preview link doesn't seem to work, but this branch deploy link works:

* https://5ef897070887c80008e4a671--shutter-new-website.netlify.app/
* You can see the behavior of the proxy working on an old link: https://5ef897070887c80008e4a671--shutter-new-website.netlify.app/preview/screenshots/

If we're good here I can merge this to master and things should work from there on.

**Comment by DarthGandalf** [comment]
The preview link https://deploy-preview-3--shutter-new-website.netlify.app/ also works now, thanks

**Comment by mheffner** [comment]
oh cool, I must have a cached version locally

**Comment by Photon89** [comment]
Works great, thanks! We should add the netlify logo here as well, I guess?

**Comment by DarthGandalf** [comment]
I think before swapping DNS need also make links more compatible with what they were, e.g. #2 and via more rewrites, when the page exists in both versions

**Comment by mheffner** [comment]
Oh yeah, I think we should continue improving this for a bit. No rush to swap the DNS until ready.

**Pull request merged**
